include:
  - fqbn: esp32:esp32:featheresp32

exclude:
  # Serial1 instance is not available for these boards.
  - sketch: examples/continuous-mode-uart/continuous-mode-uart.ino
    fqbn: 
      - arduino:avr:uno
      - arduino:avr:nano
      - infineon:xmc:kit_xmc11_boot_001
      - infineon:xmc:kit_xmc_2go_xmc1100_v1
      - infineon:xmc:kit_xmc13_boot_001
      - infineon:xmc:kit_xmc14_2go
      - infineon:xmc:kit_xmc1400_arduino
      
additional_urls:
  - core: esp32:esp32
    url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
